spring:
  application:
    name: ai-service
  data :
    mongodb:
      uri : mongodb://localhost:27017/fitnessrecommendation
      database : fitnessrecommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8083
eureka :
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client :
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/
rabbitmq:  # remember to see docker image of rabbitmq is running and in localhost:15672 we have a name of fitness.exchange
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
gemini:
  api:
    url: ${GEMINI_API_URL} # these two are set in environment  variables
    key: ${GEMINI_API_KEY}
